name: CI/CD Pipeline


on:
  push:
    branches: [ "master" ] # Runs every time you push to the 'master' branch
  pull_request:
    branches: [ "master" ]


#backend build and test
jobs:
  backend-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Build Backend
        run: |
          cd backend
          npm install
          npm run build
  
#frontend build
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install & Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

#deploy to docker hub
  docker-images:
    needs: [backend-testing, frontend-build] # Wait for previous jobs to finish
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # Only build images on actual pushes, not PRs
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Secret password from GitHub
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build/Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend #Path to the Dockerfile
          push: true
          tags: |
            romdhani01/myday-backend:1.0.${{ github.run_number }}
            romdhani01/myday-backend:latest

      - name: Build/Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend #Path to the Dockerfile
          push: true
          tags: |
            romdhani01/myday-frontend:1.0.${{ github.run_number }}
            romdhani01/myday-frontend:latest

  deploy:
       needs: docker-images
       runs-on: self-hosted
       if: github.event_name == 'push'
       steps:
         - name: Pull latest images
           run: docker compose pull

         - name: Recreate containers
           run: docker compose up -d